# Generated by Django 4.2.11 on 2024-04-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('object_name', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('altitude', models.FloatField()),
                ('azimuth', models.FloatField()),
                ('constellation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('rain_volume', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
